# Generated by Django 3.0.3 on 2020-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solutions', '0002_funcionario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
